### ISSUE TITLE
what is the error 

### ISSUE THREAD

**Issue by savan878** [Cybertat1on/NotPixel#1]
Traceback (most recent call last):
  File "C:\Users\savan\NotPixel-5\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\savan\NotPixel-5\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\savan\NotPixel-5\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "C:\Users\savan\NotPixel-5\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\savan\NotPixel-5\bot\config\config.py", line 26, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\Users\savan\AppData\Roaming\Python\Python312\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "C:\Users\savan\AppData\Roaming\Python\Python312\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
night_mode
  Extra inputs are not permitted [type=extra_forbidden, input_value='False', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
sleep_between_each_round
  Extra inputs are not permitted [type=extra_forbidden, input_value='[1000, 1500]', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
PS C:\Users\savan\NotPixel-5> ^C
PS C:\Users\savan\NotPixel-5>

**Comment by Cybertat1on** [comment]
Python version 3.12 don't support
